- name: variables in files
  hosts: local
  connection: local
  vars_file:
    - course.yaml
  tasks:
    ansible.builtin.debug:
      msg: "i am learnin {{Course}}"

 
- name: printing
  vars: #task level
      Course: cloud
  ansible.builtin.debug:
    msg: am learning {{Course}} 

- name: printing
  ansible.builtin.debug:
    msg: am learning {{Course}} 
